### PR TITLE
1999: Handle tags and assets (images) in BPI client

### PR DESCRIPTION
**Pull request by rimi-itk**
http://platform.dandigbib.org/issues/1999

### CODE REVIEW

**Comment by JrgenGNielsen** [comment]
Reviewed and approved. Awaiting merge for 2016-3

**Comment by JrgenGNielsen** [comment]
Could you fix the merge conflicts, plese?

**Comment by rimi-itk** [comment]
The merge conflict has been fixed.

**Comment by JrgenGNielsen** [comment]
reviewed and accepted

**Pull request merged**
